=== khushboogithub/SER531Assignments/Assignment1/movies.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.example.org/movies" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="moviesList">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="movie" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="title"/>
              <xs:element name="actors">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="actor" maxOccurs="unbounded" minOccurs="0"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:string" name="director"/>
              <xs:element type="xs:string" name="genre"/>
              <xs:element type="xs:short" name="academyawards" minOccurs="0"/>
              <xs:element type="xs:short" name="goldenglobeawards" minOccurs="0"/>
              <xs:element name="playingTimes">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="location"/>
                    <xs:element type="xs:string" name="time"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="xs:float" name="rating"/>
              <xs:element type="xs:string" name="reviews"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="userProfiles">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="user" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element name="moviePreferences">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="movie" maxOccurs="unbounded" minOccurs="0"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== khushboogithub/SER531Assignments/Assignment1/movies.xml
<?xml version="1.0" encoding="UTF-8"?>
<moviesList xmlns="http://www.example.org/movies" xsi:schemaLocation="http://www.example.org/movies.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<movie>
		<title>Titanic</title>
		<actors>
			<actor>Kate Winslet</actor>
			<actor>Leonardo Dicaprio</actor>
		</actors>
		<director>James Cameron</director>
		<genre>Drama</genre>
		<academyawards>2014</academyawards>
		<goldenglobeawards>2014</goldenglobeawards>
		<playingTimes>
			<location>Phoenix</location>
			<time>11AM</time>
		</playingTimes>
		<rating>9</rating>
		<reviews>You wonâ€™t mind seeing the Titanic sink all over again - in 3D exactly a hundred years from the moment it actually happened.</reviews>
	</movie>
	
	<movie>
		<title>The Hunger Games</title>
		<actors>
			<actor>Jennifer Laurance</actor>
			<actor>Liam Hemsworth</actor>
		</actors>
		<director>Gary Ross</director>
		<genre>Comedy</genre>		
		<academyawards>2016</academyawards>
		<playingTimes>
			<location>Tempe</location>
			<time>11AM</time>
		</playingTimes>
		<rating>9</rating>
		<reviews>Director Gary Ross has faithfully, lovingly adapted the first installment of Suzanne Collins' riveting dystopian trilogy.</reviews>
	</movie>

	<movie>
		<title>The Shawshank Redemption</title>
		<actors>
			<actor>Tim Robbins</actor>
			<actor>Morgan Freeman</actor>
		</actors>
		<director>Frank Darabont</director>
		<genre>Drama</genre>		
		<academyawards>2014</academyawards>
		<goldenglobeawards>2014</goldenglobeawards>
		<playingTimes>
			<location>Wisconsin</location>
			<time>11AM</time>
		</playingTimes>
		<rating>9.3</rating>
		<reviews>Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.</reviews>
	</movie>
	
	<movie>
		<title>The Dark Knight</title>
		<actors>
			<actor>Christian Bale</actor>
			<actor>Heath Ledger</actor>
		</actors>
		<director>Christopher Nolan</director>
		<genre>Drama</genre>		
		<goldenglobeawards>2016</goldenglobeawards>
		<playingTimes>
			<location>Tenesse</location>
			<time>11AM</time>
		</playingTimes>
		<rating>7</rating>
		<reviews>When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.</reviews>
	</movie>

	<userProfiles>
		<user>
			<name>Liam</name>
			<moviePreferences>
				<movie>The Dark Knight</movie>
				<movie>The Shawshank Redemption</movie>
			</moviePreferences>
		</user>
		<user>
			<name>Olivia</name>
			<moviePreferences>
				<movie>The Hunger Games</movie>
				<movie>The Shawshank Redemption</movie>
			</moviePreferences>
		</user>
		<user>
			<name>William</name>
			<moviePreferences>
				<movie>The Hunger Games</movie>
				<movie>Titanic</movie>
			</moviePreferences>
		</user>
	</userProfiles>
</moviesList>
